//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsForWebService2022_A.ServiceReferenceCogut {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCogut.WebService2022_ASoap")]
    public interface WebService2022_ASoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldResponse HelloWorld(WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldResponse> HelloWorldAsync(WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/add", ReplyAction="*")]
        int add(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> addAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subtract", ReplyAction="*")]
        int subtract(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subtract", ReplyAction="*")]
        System.Threading.Tasks.Task<int> subtractAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiply", ReplyAction="*")]
        int multiply(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiply", ReplyAction="*")]
        System.Threading.Tasks.Task<int> multiplyAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/divide", ReplyAction="*")]
        int divide(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/divide", ReplyAction="*")]
        System.Threading.Tasks.Task<int> divideAsync(int num1, int num2);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2022_ASoapChannel : WindowsFormsForWebService2022_A.ServiceReferenceCogut.WebService2022_ASoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2022_ASoapClient : System.ServiceModel.ClientBase<WindowsFormsForWebService2022_A.ServiceReferenceCogut.WebService2022_ASoap>, WindowsFormsForWebService2022_A.ServiceReferenceCogut.WebService2022_ASoap {
        
        public WebService2022_ASoapClient() {
        }
        
        public WebService2022_ASoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2022_ASoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2022_ASoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2022_ASoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldResponse WindowsFormsForWebService2022_A.ServiceReferenceCogut.WebService2022_ASoap.HelloWorld(WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequest inValue = new WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequest();
            inValue.Body = new WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequestBody();
            WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldResponse retVal = ((WindowsFormsForWebService2022_A.ServiceReferenceCogut.WebService2022_ASoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldResponse> WindowsFormsForWebService2022_A.ServiceReferenceCogut.WebService2022_ASoap.HelloWorldAsync(WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequest inValue = new WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequest();
            inValue.Body = new WindowsFormsForWebService2022_A.ServiceReferenceCogut.HelloWorldRequestBody();
            return ((WindowsFormsForWebService2022_A.ServiceReferenceCogut.WebService2022_ASoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int add(int num1, int num2) {
            return base.Channel.add(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> addAsync(int num1, int num2) {
            return base.Channel.addAsync(num1, num2);
        }
        
        public int subtract(int num1, int num2) {
            return base.Channel.subtract(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> subtractAsync(int num1, int num2) {
            return base.Channel.subtractAsync(num1, num2);
        }
        
        public int multiply(int num1, int num2) {
            return base.Channel.multiply(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> multiplyAsync(int num1, int num2) {
            return base.Channel.multiplyAsync(num1, num2);
        }
        
        public int divide(int num1, int num2) {
            return base.Channel.divide(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> divideAsync(int num1, int num2) {
            return base.Channel.divideAsync(num1, num2);
        }
    }
}
